# Generated by Django 4.2 on 2026-04-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_price_ks',
            field=models.PositiveIntegerField(default=0, help_text='Original price (for discount display)'),
        ),
    ]
