# Generated by Django 4.2 on 2026-04-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_original_price_ks'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_days',
            field=models.PositiveIntegerField(default=14, help_text='Delivery time in days'),
        ),
    ]
