# Generated by Django 4.2 on 2026-04-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_delivery_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('kindle', 'Amazon Kindle'), ('kobo', 'Kobo'), ('boox', 'Boox'), ('bigme', 'Bigme')], default='kindle', max_length=20),
        ),
    ]
