# Generated by Django 4.2 on 2026-04-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['brand', 'name']},
        ),
        migrations.AddField(
            model_name='product',
            name='device_model',
            field=models.CharField(choices=[('kindle_paperwhite_12', 'Kindle Paperwhite 12th Gen (2024)'), ('kindle_paperwhite_sig', 'Kindle Paperwhite Signature Edition'), ('kindle_basic', 'Kindle Basic (2022)'), ('kindle_colorsoft', 'Kindle Colorsoft'), ('kindle_scribe', 'Kindle Scribe'), ('kobo_clara_bw', 'Kobo Clara BW'), ('kobo_clara_colour', 'Kobo Clara Colour'), ('kobo_libra_colour', 'Kobo Libra Colour'), ('kobo_sage', 'Kobo Sage'), ('boox_palma_2', 'Boox Palma 2'), ('boox_go_color_7', 'Boox Go Color 7'), ('boox_note_air_3', 'Boox Note Air 3'), ('bigme_b7', 'Bigme B7'), ('bigme_hibreak_pro', 'Bigme Hibreak Pro Color')], default='kindle_paperwhite_12', max_length=50),
        ),
    ]
