# Generated by Django 4.2 on 2026-04-21 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_options_product_device_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('kindle', 'Amazon Kindle'), ('kobo', 'Kobo'), ('boox', 'Boox'), ('bigme', 'Bigme')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['brand', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='device_model',
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_days',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price_ks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='preorder',
            name='device_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preorders', to='products.devicemodel'),
        ),
        migrations.AddField(
            model_name='product',
            name='compatible_models',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.devicemodel'),
        ),
    ]
