# Generated by Django 4.2 on 2026-04-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_title',
            field=models.CharField(blank=True, help_text='Longer title displayed below the main name', max_length=500),
        ),
    ]
