# Generated by Django 4.2 on 2026-04-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_full_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('covers', 'Kindle Covers'), ('chargers', 'Chargers & Cables'), ('batteries', 'Batteries'), ('screen_guards', 'Screen Guards'), ('stands', 'Stands'), ('stickers', 'Stickers & Skins'), ('other', 'Other Accessories')], default='covers', max_length=20),
        ),
    ]
